version: '3.8'

services:
  web:
    image: micpostyam/prepcertif:latest
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`certif.ustudyguide.com`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"

networks:
  web:
    external: true