version: '3.8'

services:
  web:
    image: micpostyam/prepcertif:latest
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.certif-ustudyguide.rule=Host(`certif.ustudyguide.com`)"
      - "traefik.http.routers.certif-ustudyguide.entrypoints=websecure"
      - "traefik.http.services.certif-ustudyguide.loadbalancer.server.port=3000"
      - "traefik.http.routers.certif-ustudyguide.tls=true"

networks:
  web:
    external: true